const {createData} = require("./importer");

// TODO: Add parameters path here
const jsonPath = "./data/smallData.json"
const equipName = "Equipment1"
const startTime = "10:28"
const endTime = "16:15"

let jsonData = require(jsonPath);

// Check if jsonData is generated by dataGenerator
if (jsonData.input) {
    jsonData = jsonData.input;
}

let {plants, equipments, sensors} = createData(jsonData);

function getAllSensors(equipment_id, start_time, end_time) {
    let result = {};
    let equipment = equipments["Equipment1"];
    let filteredSensors = equipment.getAllSensorInTimeRange(start_time, end_time);
    filteredSensors.forEach((obj) => {
        let obj_result = result[obj.sensor.name];
        if (obj_result === undefined) {
            obj_result = [];
            result[obj.sensor.name] = obj_result;
        }
        obj_result.push([obj.startTimeStr, obj.endTimeStr])
    })
    return JSON.stringify(result);
}

console.log(getAllSensors(equipName, startTime, endTime));
